// server/workers/adminAnalysisWorker.js
const { workerData } = require('worker_threads');
const mongoose = require('mongoose');
const path = require('path');

const AdminDocument = require('../models/AdminDocument');
const connectDB = require('../config/db');
const geminiService = require('../services/geminiService');
const ollamaService = require('../services/ollamaService'); // <-- Import ollamaService
const { ANALYSIS_PROMPTS } = require('../config/promptTemplates');

require('dotenv').config({ path: path.resolve(__dirname, '..', '.env') });

async function performAdminDocAnalysis(adminDocumentId, originalName, textForAnalysis, llmProvider) { // <-- Receive provider
    const logPrefix = `[AdminAnalysisWorker ${process.pid}, Doc: ${originalName}]`;
    console.log(`${logPrefix} Starting analysis using provider: ${llmProvider}. Text length: ${textForAnalysis ? textForAnalysis.length : 0}`);

    const analysisResults = { faq: "", topics: "", mindmap: "" };
    let allIndividualAnalysesSuccessful = true;

    // --- DYNAMIC LLM SERVICE SELECTION ---
    const serverApiKey = process.env.GEMINI_API_KEY;
    const serverOllamaUrl = process.env.OLLAMA_API_BASE_URL;

    if (llmProvider === 'gemini' && !serverApiKey) {
        const errorMessage = "Error generating analysis: Server's GEMINI_API_KEY is not configured.";
        console.error(`${logPrefix} FATAL: ${errorMessage}`);
        return { success: false, results: { faq: errorMessage, topics: errorMessage, mindmap: errorMessage } };
    }
    if (llmProvider === 'ollama' && !serverOllamaUrl) {
        const errorMessage = "Error generating analysis: Server's OLLAMA_API_BASE_URL is not configured.";
        console.error(`${logPrefix} FATAL: ${errorMessage}`);
        return { success: false, results: { faq: errorMessage, topics: errorMessage, mindmap: errorMessage } };
    }
    // --- END DYNAMIC SELECTION ---

    async function generateSingleAnalysis(type, promptContentForLLM) {
        try {
            console.log(`${logPrefix} Generating ${type} with ${llmProvider}...`);
            const historyForLlm = [{ role: 'user', parts: [{ text: "Perform the requested analysis based on the system instruction and provided document text." }] }];
            
            let generatedText;
            if (llmProvider === 'ollama') {
                generatedText = await ollamaService.generateContentWithHistory(
                    historyForLlm, promptContentForLLM, null, { ollamaUrl: serverOllamaUrl }
                );
            } else { // Default to Gemini
                generatedText = await geminiService.generateContentWithHistory(
                    historyForLlm, promptContentForLLM, null, { apiKey: serverApiKey }
                );
            }

            if (!generatedText || typeof generatedText !== 'string' || generatedText.trim() === "") {
                console.warn(`${logPrefix} LLM (${llmProvider}) returned empty content for ${type}.`);
                return { success: false, content: `Notice: No content generated by the AI for ${type}.` };
            }
            console.log(`${logPrefix} ${type} generation successful.`);
            return { success: true, content: generatedText.trim() };
        } catch (error) {
            console.error(`${logPrefix} Error during ${type} generation with ${llmProvider}: ${error.message}`);
            allIndividualAnalysesSuccessful = false;
            return { success: false, content: `Error generating ${type}: ${error.message.split('\n')[0].substring(0, 250)}` };
        }
    }
    
    // ... (rest of the analysis logic remains the same) ...
    if (!textForAnalysis || textForAnalysis.trim() === "") {
        console.warn(`${logPrefix} No text provided for analysis. Skipping generation.`);
        analysisResults.faq = "Skipped: No text content provided.";
        analysisResults.topics = "Skipped: No text content provided.";
        analysisResults.mindmap = "Skipped: No text content provided.";
    } else {
        const analysisPromises = [
            generateSingleAnalysis('FAQ', ANALYSIS_PROMPTS.faq.getPrompt(textForAnalysis)),
            generateSingleAnalysis('Topics', ANALYSIS_PROMPTS.topics.getPrompt(textForAnalysis)),
            generateSingleAnalysis('Mindmap', ANALYSIS_PROMPTS.mindmap.getPrompt(textForAnalysis))
        ];
        const outcomes = await Promise.all(analysisPromises);
        analysisResults.faq = outcomes[0].content;
        analysisResults.topics = outcomes[1].content;
        analysisResults.mindmap = outcomes[2].content;
    }
    
    try {
        await AdminDocument.updateOne({ _id: adminDocumentId }, {
            $set: {
                "analysis.faq": analysisResults.faq,
                "analysis.topics": analysisResults.topics,
                "analysis.mindmap": analysisResults.mindmap,
                "analysisUpdatedAt": new Date()
            }
        });
        console.log(`${logPrefix} Analysis results stored in DB.`);
        return { success: allIndividualAnalysesSuccessful, message: `Analysis ${allIndividualAnalysesSuccessful ? 'completed' : 'completed with some failures'}.`, results: analysisResults };
    } catch (dbError) {
        console.error(`${logPrefix} DB Error storing analysis results:`, dbError);
        return { success: false, message: `DB Error storing analysis: ${dbError.message}`, results: analysisResults };
    }
}

async function run() {
    // --- READ llmProvider FROM workerData ---
    const { adminDocumentId, originalName, textForAnalysis, llmProvider } = workerData;
    let dbConnected = false;
    let overallTaskSuccess = false;

    try {
        await connectDB(process.env.MONGO_URI);
        dbConnected = true;
        const analysisServiceResult = await performAdminDocAnalysis(adminDocumentId, originalName, textForAnalysis, llmProvider);
        overallTaskSuccess = analysisServiceResult.success;
    } catch (error) {
        console.error(`[AdminAnalysisWorker] Critical error in worker:`, error);
    } finally {
        if (dbConnected) {
            await mongoose.disconnect();
        }
        console.log(`[AdminAnalysisWorker] Finished task for ${originalName}. Overall Success: ${overallTaskSuccess}`);
    }
}

run();
